language: java
addons:
  firefox: latest
jdk:
  - oraclejdk8
before_install:
  - pip install --user codecov
  	- "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
after_success:
  - codecov
